### ISSUE TITLE
cv2.cv2 has no attribute 'pythoncuda' ?

### ISSUE THREAD

**Issue by muhdlaziem** [NeerajGulia/python-opencv-cuda#4]
(DRenv) $USER@pop-os:~/Workspace/FYP/DR/python-opencv-cuda/python$ python cpu-opt_flow.py
Traceback (most recent call last):
  File "cpu-opt_flow.py", line 4, in <module>
    cm.findOpticalFlow('video/vtest.avi', 'video/cpu_output.avi', False, False)
  File "/home/muhdlaziem/Workspace/FYP/DR/python-opencv-cuda/python/common.py", line 63, in findOpticalFlow
    flow = cv2.pythoncuda.cpuOpticalFlowFarneback(g_prev, g_next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
AttributeError: module 'cv2.cv2' has no attribute 'pythoncuda'

(DRenv) $USER@pop-os:~/Workspace/FYP/DR/python-opencv-cuda/python$ python gpu-opt_flow.py 
Traceback (most recent call last):
  File "gpu-opt_flow.py", line 4, in <module>
    cm.findOpticalFlow('video/vtest.avi', 'video/cpu_output.avi', True, False)
  File "/home/muhdlaziem/Workspace/FYP/DR/python-opencv-cuda/python/common.py", line 60, in findOpticalFlow
    flow = cv2.pythoncuda.gpuOpticalFlowFarneback(g_prev, g_next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
AttributeError: module 'cv2.cv2' has no attribute 'pythoncuda'

**Comment by marianbrunet** [comment]
Similar situation.
When I run:     python cpu-opt_flow.py 

I get:

Traceback (most recent call last):
  File "cpu-opt_flow.py", line 4, in <module>
    cm.findOpticalFlow('video/vtest.avi', 'video/cpu_output.avi', False, False)
  File "/home/maria/Downloads/python-opencv-cuda/python/common.py", line 63, in findOpticalFlow
    flow = cv2.pythoncuda.cpuOpticalFlowFarneback(g_prev, g_next, None, 0.5, 3, 15, 3, 5, 1.2, 0)
AttributeError: 'module' object has no attribute 'pythoncuda'

**Comment by rgov** [comment]
You need to compile OpenCV with the provided extra files.

**Comment by rgov** [comment]
Perhaps this is not needed anymore, because you can use 

```python
flowcomputer = cv2.cuda_FarnebackOpticalFlow.create(...)
flow = flowcomputer.calc(cv2.cuda_GpuMat(im1), cv2.cuda_GpuMat(im2), None).download()
```

Pay close attention to the order you pass arguments to `create` because it is not the same as the CPU function.
